/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTestingArgs } from "./CreateTestingArgs";
import { UpdateTestingArgs } from "./UpdateTestingArgs";
import { DeleteTestingArgs } from "./DeleteTestingArgs";
import { TestingFindManyArgs } from "./TestingFindManyArgs";
import { TestingFindUniqueArgs } from "./TestingFindUniqueArgs";
import { Testing } from "./Testing";
import { TestingService } from "../testing.service";

@graphql.Resolver(() => Testing)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TestingResolverBase {
  constructor(
    protected readonly service: TestingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Testing",
    action: "read",
    possession: "any",
  })
  async _testingsMeta(
    @graphql.Args() args: TestingFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Testing])
  @nestAccessControl.UseRoles({
    resource: "Testing",
    action: "read",
    possession: "any",
  })
  async testings(
    @graphql.Args() args: TestingFindManyArgs
  ): Promise<Testing[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Testing, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Testing",
    action: "read",
    possession: "own",
  })
  async testing(
    @graphql.Args() args: TestingFindUniqueArgs
  ): Promise<Testing | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Testing)
  @nestAccessControl.UseRoles({
    resource: "Testing",
    action: "create",
    possession: "any",
  })
  async createTesting(
    @graphql.Args() args: CreateTestingArgs
  ): Promise<Testing> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Testing)
  @nestAccessControl.UseRoles({
    resource: "Testing",
    action: "update",
    possession: "any",
  })
  async updateTesting(
    @graphql.Args() args: UpdateTestingArgs
  ): Promise<Testing | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Testing)
  @nestAccessControl.UseRoles({
    resource: "Testing",
    action: "delete",
    possession: "any",
  })
  async deleteTesting(
    @graphql.Args() args: DeleteTestingArgs
  ): Promise<Testing | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
